require("judgepmjq")
require("sht20")
require("pmjq")
sht20.initSHT20()
tmr.alarm(0,6000,1,function()
     PM,JQ= pmjq.readpm25jq()
	 judgepmjq.disp(PM,JQ)
     SHumi=sht20.readHumi()
     STemp=sht20.readTemp()
	 display.dispall(PM,JQ,STemp,SHumi)
end)
require("httpclient")
tmr.alarm(2, 30000, 1, function()
    httpclient.SendValue(STemp,SHumi,PM,JQ)
    end)
collectgarbage()

